### ISSUE TITLE
Unable to use DataType.String as primary key

### ISSUE THREAD

**Issue by estyrke** [milvus-io/milvus-sdk-node#189]
**Describe the bug:**

The createCollection function fails if supplying a primary key field with a string type. According to the docs this should be supported: https://milvus.io/docs/create_collection.md

**Steps to reproduce:**

1.  ```javascript
    await client.createCollection({
      collection_name: 'coll',
      fields: [{ name: 'id', data_type: DataType.String, is_primary_key: true }],
    });
    ```

Gives 
```
Error: The `data_type` for the primary key field must be DataType.Int64.

    at checkCollectionFields (node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.2.15/node_modules/@zilliz/milvus2-sdk-node/milvus/utils/Validate.ts:82:11)
    at MilvusClient.<anonymous> (node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.2.15/node_modules/@zilliz/milvus2-sdk-node/milvus/grpc/Collection.ts:110:26)
    at Generator.next (<anonymous>)
    at node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.2.15/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Collection.js:8:71
    at new Promise (<anonymous>)
    at Object.<anonymous>.__awaiter (node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.2.15/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Collection.js:4:12)
    at MilvusClient._createCollection (node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.2.15/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Collection.js:74:16)
    at MilvusClient.<anonymous> (node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.2.15/node_modules/@zilliz/milvus2-sdk-node/milvus/MilvusClient.ts:82:25)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.2.15/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/MilvusClient.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Milvus-node-sdk version:**
3.2.15

**Milvus version:**
3.2.9

**Comment by shanghaikid** [comment]
Hi, please use `DataType.VarChar` . 

DataType.String is not supported yet. 

The doc is wrong, I will update that doc.

**Comment by shanghaikid** [comment]
Here is an example

https://github.com/milvus-io/milvus-sdk-node/blob/main/examples/milvus/HelloMilvus.ts

**Comment by shanghaikid** [comment]
And the error message should be improved.

**Comment by estyrke** [comment]
Thanks for the quick reply! Given the followup errors I got, I assume that DataType.String is not supported for non-primary fields either? I will change to VarChar. :)

**Comment by shanghaikid** [comment]
> Thanks for the quick reply! Given the followup errors I got, I assume that DataType.String is not supported for non-primary fields either? I will change to VarChar. :)

Yeah. Milvus only support VarChar now.
