### ISSUE TITLE
getVersion Should be removed from API?

### ISSUE THREAD

**Issue by teetering** [milvus-io/milvus-sdk-node#198]
**Describe the bug:**
I noticed I recently started receiving the below error when calling `getVersion` using our zilla-hosted Milvus instance. After talking to their support, they claim that this api is no longer supported on newer versions of Milvus (why??). I guess this means it should be removed from milvus-sdk-node?

```
Rejection - {
    "stack": "Error: 2 UNKNOWN: it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/GetVersion
    at callErrorFromStatus (/media/data0/dev/proj/node/node_modules/@grpc/grpc-js/build/src/call.js:31:19)
    at Object.onReceiveStatus (/media/data0/dev/proj/node/node_modules/@grpc/grpc-js/build/src/client.js:192:76)
    at /media/data0/dev/proj/node/node_modules/@grpc/grpc-js/build/src/call-interface.js:78:35
    at Object.onReceiveStatus (/media/data0/dev/proj/node/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Grpc.js:180:29)
    at InterceptingListenerImpl.onReceiveStatus (/media/data0/dev/proj/node/node_modules/@grpc/grpc-js/build/src/call-interface.js:73:23)
    at Object.onReceiveStatus (/media/data0/dev/proj/node/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:360:141)
    at Object.onReceiveStatus (/media/data0/dev/proj/node/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /media/data0/dev/proj/node/node_modules/@grpc/grpc-js/build/src/resolving-call.js:94:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
for call at
    at ServiceClientImpl.makeUnaryRequest (/media/data0/dev/proj/node/node_modules/@grpc/grpc-js/build/src/client.js:160:34)
    at ServiceClientImpl.<anonymous> (/media/data0/dev/proj/node/node_modules/@grpc/grpc-js/build/src/make-client.js:105:19)
    at /media/data0/dev/proj/node/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:20:24
    at new Promise (<anonymous>)
    at promisify (/media/data0/dev/proj/node/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Function.js:17:17)
    at MilvusClient.<anonymous> (/media/data0/dev/proj/node/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:183:44)
    at Generator.next (<anonymous>)
    at /media/data0/dev/proj/node/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/media/data0/dev/proj/node/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/GrpcClient.js:4:12)",
    "message": "2 UNKNOWN: it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/GetVersion",
    "code": 2,
    "details": "it's a deny api, fullMethod:/milvus.proto.milvus.MilvusService/GetVersion",
    "metadata": {
        "content-type": [
            "application/grpc"
        ],
        "via": [
            "1.1 google"
        ],
        "date": [
            "Thu, 06 Jul 2023 17:38:36 GMT"
        ],
        "content-length": [
            "0"
        ],
        "alt-svc": [
            "h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"
        ]
    }
}
```

**Comment by shanghaikid** [comment]
zilliz cloud doesn't support this api, since it may uses different milvus than the open-source one.
