### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'nq')

### ISSUE THREAD

**Issue by iGmainC** [milvus-io/milvus-sdk-node#404]
**Describe the bug:**
TypeError: Cannot read properties of undefined (reading 'nq')

**Steps to reproduce:**

1. init empty node project
2. `pnpm i -D tsx`，`pnpm i @zilliz/milvus2-sdk-node`
3. create `main.ts`: 
```ts
import { DataType, MilvusClient } from "@zilliz/milvus2-sdk-node";

let client = new MilvusClient({
    address: "localhost:19530",
    username: "root",
    password: "123456789",
});

const collection_name = "testTable1";

async function initMilvus() {
    await client.useDatabase({ db_name: "vector_db" });
    let r = await client.createCollection({
        collection_name,
        description: '',
        enableDynamicField: true, // 是否启用动态字段
        fields: [
            {
                name: 'id',
                data_type: DataType.Int64,
                is_primary_key: true,
                autoID: true,
            },
            { name: 'embedding', data_type: DataType.FloatVector, dim: 1024 },
            {
                name: 'chunk',
                data_type: DataType.VarChar,
                max_length: 2048,
                enable_match: true,
                enable_analyzer: true,
                analyzer_params: { type: "chinese" }
            },
        ],
        index_params: [
            {
                field_name: 'embedding',
                index_name: 'embedding_HNSW',
                index_type: 'HNSW',
                metric_type: 'IP',
                params: { efConstruction: 32, M: 64 },
            },
        ],
    });
    console.log(r);
    return r;
}

async function main() {
    await initMilvus()
    await client.useDatabase({ db_name: "vector_db" });
    let r = await client.search({
        collection_name,
        data: ['工作地点在公司内部'],
        anns_field: 'chunk',
        limit: 3,
        params: { 'drop_ratio_search': 0.2 }
    })
    console.log(r);

}

(async () => {
    await main();
})();
```
4. `tsx main.ts`
5. 
```
➜  milvus-demo pnpm start

> milvus-demo@1.0.0 start /home/xxx/milvus-demo
> tsx src/main.ts

{
  extra_info: {},
  error_code: 'Success',
  reason: '',
  code: 0,
  retriable: false,
  detail: ''
}
/home/xxx/milvus-demo/node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.5.3/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/utils/Format.js:705
        nq: requests[0].nq,
                        ^

TypeError: Cannot read properties of undefined (reading 'nq')
    at buildSearchRequest (/home/xxx/milvus-demo/node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.5.3/node_modules/@zilliz/milvus2-sdk-node/milvus/utils/Format.ts:909:21)
    at MilvusClient.<anonymous> (/home/xxx/milvus-demo/node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.5.3/node_modules/@zilliz/milvus2-sdk-node/milvus/grpc/Data.ts:506:78)
    at Generator.next (<anonymous>)
    at fulfilled (/home/xxx/milvus-demo/node_modules/.pnpm/@zilliz+milvus2-sdk-node@2.5.3/node_modules/@zilliz/milvus2-sdk-node/dist/milvus/grpc/Data.js:5:58)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)

Node.js v22.12.0
 ELIFECYCLE  Command failed with exit code 1.
```

**Milvus-node-sdk version:** 2.5.3

**Milvus version:** 2.5.1

**Comment by shanghaikid** [comment]
you need to define functions to enable full text search. 

1. add an sparse field in your schema
```javascript
{
    name: "sparse",
    data_type: DataType.SparseFloatVector,
 }
```

2. add functions in your create collection params
```javascript
const functions = [
    {
      name: 'text_bm25_emb',
      description: 'bm25 function',
      type: FunctionType.BM25,
      input_field_names: ['chunk'],
      output_field_names: ['sparse'],
      params: {},
    },
]；
```

3. the anns field name should be the spare field
```javascript
let r = await client.search({
        collection_name,
        data: ['工作地点在公司内部'],
        anns_field: 'sparse',
        limit: 3,
        params: { 'drop_ratio_search': 0.2 }
    })
```

**Comment by shanghaikid** [comment]
or you can use attu to create the collection and index for you 

https://github.com/zilliztech/attu

**Comment by iGmainC** [comment]
> you need to define functions to enable full text search.
> 
>     1. add an sparse field in your schema
> 
> 
> ```js
> {
>     name: "sparse",
>     data_type: DataType.SparseFloatVector,
>  }
> ```
> 
>     2. add functions in your create collection params
> 
> 
> ```js
> const functions = [
>     {
>       name: 'text_bm25_emb',
>       description: 'bm25 function',
>       type: FunctionType.BM25,
>       input_field_names: ['chunk'],
>       output_field_names: ['sparse'],
>       params: {},
>     },
> ]；
> 
> client. createCollection({
> ...otherparams,
> functions
> })
> ```
> 
>     3. update index using bm25
> 
> 
> ```js
> {
>                 field_name: 'sparse',
>                 index_name: 'sparse',
>                 index_type: 'AUTOINDEX',
>                 metric_type: 'BM25',
> }
> ```
> 
>     4. the anns field name should be the spare field
> 
> 
> ```js
> let r = await client.search({
>         collection_name,
>         data: ['工作地点在公司内部'],
>         anns_field: 'sparse',
>         limit: 3,
>         params: { 'drop_ratio_search': 0.2 }
>     })
> ```

This solved my problem.
